spring:
  application:
    name: order-service

  data:
    mongodb:
      uri: mongodb://localhost:27017/orderdb

server:
  port: 8085

product:
  service:
    url: http://localhost:8050

user:
  service:
    url: http://localhost:8095